Repository Marak/colors.js, pull requests merged in 2018-02, with the labels that each got.

#184 Update stringPrototypeBlacklist object
  lib/extendStringPrototype.js
Labels: ready to merge

#185 Adding badges npm, dependencies and devDependencies
  ReadMe.md
Labels: documentation

#172 Update supports-colors.js
  lib/system/has-flag.js
  lib/system/supports-colors.js
Labels: critical bug, ready to merge

#203 Remove setTheme dynamic require(...) that is problematic with webpack
  examples/normal-usage.js
  lib/colors.js
Labels: critical bug
